name: Playwright Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar browsers de Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas Cucumber con Playwright
        run: npm run test:formulario
        env:
          CI: true

      - name: Configurar GitHub Pages
        if: always()
        uses: actions/configure-pages@v5

      - name: Subir reporte a Pages
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports/html-report

      - name: Publicar GitHub Pages
        if: always()
        uses: actions/deploy-pages@v4